language: node_js
node_js:
- '0.10'
services:
- redis-server
- mongodb
before_script:
script: npm run-script test-travis
after_script:
- npm install -g coveralls@2
- cat ./coverage/lcov.info | coveralls
- npm install -g codeclimate-test-reporter
- cat ./coverage/lcov.info | codeclimate
addons:
  code_climate:
    repo_token:
      secure: ""
